config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :posts, :products, :orders
  
  resources :shops, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
  
  get 'shops/result' => 'shops#result', as: "result"
  get '/pay/:id' => 'shops#pay'
  get  '/near_shop' => 'shopw#near_shop'
  post '/write'=> 'shops#write'
  get "/location" => "shops#location"
  post 'shops/near_shop'
    
  
  
  get 'products/index' => 'products#index'
  
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  get 'line_items/check_order' => 'line_items#check_order', as: "my_order"
  get 'line_items/new/:id' => 'line_items#new', as: "line_items_new"
  get 'line_items/okay' => 'line_items#okay', as: "okay"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post '/line_items/:product_id' => "line_items#create"
  post 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  get 'okay/accept/:id' => 'line_items#accept',as: "accept"
  get 'okay/deny/:id' => 'line_items#deny',as: "deny"
  
  get '/orders/index' => "orders#index"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      if user.nil? 
        can :read, :all
      elsif user.has_role? 'customer'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
      elsif user.has_role? 'manager'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
      elsif user.has_role? 'admin'
      can [:read, :create, :update, :destroy], :all
      
      elsif user.has_role? 'manager'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
        
      elsif user.has_role? 'admin'
        can [:read, :create, :update, :destroy], :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :shop
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  belongs_to :shop
  belongs_to :user
  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    resourcify
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    belongs_to :shop
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base
    # 여러 메뉴를 가지고 있다
    has_many :menus
    has_many :products
    has_many :comments
    has_many :favorite
    has_many :users, through: :favorite
    
    def self.search(search)
      where("name LIKE ?", "%#{search}%") 
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorite
  has_many :shops, through: :favorite
  has_many :posts
  has_many :favorites
  has_many :comments
  has_many :line_items
  
  after_create :assign_default_role
  def assign_default_role
    self.add_role(:customer) if self.roles.blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  
  def location
    # render layout: false
  end
  
  def near_shop
      @current_lat = params[:lat]
      @current_lon = params[:long]
      @shop = Shop.select("id, Name, (6371*acos(cos(radians("+@current_lat+"))*cos(radians(Latitude))*cos(radians(Longtitude)-radians("+@current_lon+"))+sin(radians("+@current_lat+"))*sin(radians(Latitude)))) AS Distance").group("Distance").having("Distance < ?", 2)  
      # p @lat.to_i - @long.to_i
      
  end
  
  def index
    @shops = Shop.all
  end

  def show
    if current_user == nil
      redirect_to '/users/sign_in'
    else
    @shop = Shop.find(params[:id])
    @products = Product.where(shop_id: params[:id])
    @comments = Comment.where(shop_id: params[:id])
    @average = @comments.average(:stars)
    @favorite = Favorite.find_by(shop_id: @shop.id, user_id: current_user.id)
    end
  end
  
  def pay
    
    @selected_product = Product.find_by_id(params[:id])
    @products = Product.where(id: params[:id])
    
  end
  
  def result
    # @shops = Shop.all
    if params[:search]
      @shops = Shop.search(params[:search]).order("created_at DESC")
    else
      @shops = Shop.all.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<%= stylesheet_link_tag "list.css" %>

<div class="sub-content">
<!--나중에 지울 것!!-->
<div id=menu>
  <div class="mini-gap"></div>
    <img src="/image/cafe.png">
    <div class="search">
    <%= form_tag(result_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Cafes", :style => "color: black" %>
      <!--<%= submit_tag "Search", :name => nil %>-->
      <%= button_tag(type: "submit", class: "btn pink") do %>Search<i class="icon-repeat"></i><% end %>
    <% end %>
    </div>
    <div class="gap"></div>
  <% @shops.each do |p| %>
    <a href = "/shops/<%= p.id %>" class="text"><%= p.name %></a>
  <% end %>
  </div>
    

</div>

app/views/shops/location.html.erb
    <style type="text/css">
        
        .loading {
            width: 100%;
            height: 100%;
            position: absolute;
            top: -4px;
            
            left: 0;
            z-index: 99999;
            background: rgba(0, 0, 0, 0.5);
            display: none;
        }
       
        .loading p {
            position: relative;
            top: 50%;
            margin: -75px auto 0 auto;
            width: 200px;
            height: 50px;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            background: #fff;
            box-sizing: border-box;
            padding: 0 30px;
            text-align: center;
            font-size: 16px;
            color: #555;
        }
        .loading p strong {
            display: block;
            padding-top: 15px;
           
          
        }
    </style>
</head>
<body>
 
<div id="wrap">
<!--    loading-->
    <section class="loading">
        <p>
            <strong>로딩중...</strong>
        </p>
    </section>
</div>
 
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
 
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 
<script type="text/javascript">
$(document).ready(function() {
    console.log('로딩 활성화');
    $('.loading').show();
});
 
$(window).on('load', function() {
    console.log('로딩 비활성화');
    $('.loading').hide();
});
</script>


<script>

  var current_lat;
  var current_lon;
  

  // window.onload=function(){
  ;(function($) {
    //위치정보를 확인할 수 있는 브라우저인지 확인
    if(navigator.geolocation == undefined){
        alert("위치 정보 기능을 지원하지 않습니다!")
        return;
    }
    navigator.geolocation.getCurrentPosition(success, fail); //현재 위치 정보를 조사하고 성공 실패 했을시 호출되는 함수 설정
})(jQuery);
 
//현재 위치 정보 알아보는 메소드
// function showData(){
//     navigator.geolocation.getCurrentPosition(success, fail); //현재 위치 정보를 조사하고 성공 실패 했을시 호출되는 함수 설정
    
// }
 
    function success(position) { //성공시
       
        current_lat=position.coords["latitude"];
        current_lon=position.coords["longitude"];

        // log("위치정보 확인 성공!");
        // window.alert("성공");
        // log("latitude:"+current_lat);
        // log("longitude:"+current_lon);
        // window.alert(current_lat +","+ current_lon);
        
        //  $.post("/", { lat: current_lat, long: current_lon } ).done(function() { alert("Success, do the redirection here!"); });



    function post_goto(url, parm, target){ 
     var f = document.createElement('form'); 
     var objs, value; 
     for(var key in parm){ 
     value = parm[key]; 
     objs = document.createElement('input'); 
     objs.setAttribute('type', 'hidden'); 
     objs.setAttribute('name', key); 
     objs.setAttribute('value', value); 
     f.appendChild(objs); 
     } 
     if(target) 
     f.setAttribute('target', target); 
     
     f.setAttribute('method', 'post'); 
     f.setAttribute('action', url); 
     document.body.appendChild(f); 
     f.submit(); 
    }    
    post_goto('/shops/near_shop', {lat : current_lat, long : current_lon} )

        //window.open("near_shop.html?lat:"+current_lat+"lon:"+current_lon);
       
        
    }
        
 
    //실패시
    function fail(err){
        switch (err.code){
            case err.PERMISSION_DENIED:
                msg = "사용자 거부";
            break;
 
            case err.PERMISSION_UNAVAILABLE:
                msg = "지리정보를 얻을 수 없음";
            break;
 
            case err.TIMEOUT:
                msg = "시간초과";
            break;
 
            case err.UNKNOWN_ERROR:
                msg = "알 수 없는 오류 발생";
            break;
        }
            log(msg);
    }
  
      // function log(msg){
      //   var console = document.getElementById("console");
      //   console.innerHTML += msg+"<br/>";
      // }


</script>

app/views/shops/near_shop.html.erb
<%= stylesheet_link_tag "list.css" %>


<!-- Main Menu Screen -->
<div class="sub-content">
<div id=menu>
    <div class="mini-gap"></div>
    <img src="/image/cafe.png">

    <!--<a id="newgame_menu">new game</a>-->
    <!--<a id="setting_menu">settings</a>-->
    <% @shop.each do |p| %>
     <a href = "/show_product/<%= p.id %>" style= "font-size: 30px"><%= p.Name %></a>
  <% end %>
</div>
</div>

<!--
<div id="debug" style="font-size: 16px; color: #FFF;"></div>
-->

app/views/shops/pay.html.erb
<div class="sub-content">
  <% if flash[:notice] %>
    <div class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% @products.each do |product| %>
  
  <form action = "/line_items/<%= product.id %>" method = "post">
    
        <h3>이름 : <%= product.name %></h3>
        <h3>가격 : <%= product.price %>원</h3>
          수량 : <input type = "number" min = "1" max = "100" step = "1" name = "quantity">
          사이즈 S<input type = "radio" name = "size" value = "S"/>
                M<input type = "radio" name = "size" value = "M"/>
                L<input type = "radio" name = "size" value = "L"/>
                <input type="hidden" name="shop_id" value= <%= product.shop_id %>>
   
  <!--<div class="btn-group btn-group-justified footer" role="group" aria-label="...">-->
    <div class="gap"></div>
    <div class="btn-group" role="group">
      <input type = "submit" value = "장바구니!" class = "btn pink"/>
    </div>
    <div class="btn-group" role="group">
      <button type="button", class="btn green">바로 결제</button>
    </div>
    
  </form>
  </div>
  <% end %>
</div>

app/views/shops/result.html.erb
<%= stylesheet_link_tag "list.css" %>
<br><br>



<div id=menu>
  <div class="mini-gap"></div>
    <img src="/image/cafe.png">
<% @shops.each do |p| %>
  <%= p.name, shop_path(p) %>
<% end %>
  </div>
</div>

app/views/shops/show.erb
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
  <%= stylesheet_link_tag "list.css" %>
  <div class="sub-content">
    
  <h2><%= @shop.name %></h2> <a href = '/shops'><h4>Return List</h4></a>
   <div id=menu>
    <div class="mini-gap"></div>
    <img src="/image/menu.png">
  <% @products.each do |product| %>
    <a href = '/pay/<%= product.id %>'><%= product.name %></a>
  <% end %>
  </div>
<div class= "blocks">
<div class="mini-gap"></div>
  <% if @favorite.present? == false %>
    <form action='/shops/<%= @shop.id %>/favorites' method="post">
      <input class="img" type="image"  src="/image/d_heart.png" onsubmit="submit();" />
    </form>
  <% else %>
    <%= link_to "삭제하기", shop_favorite_path(shop_id: @shop.id), method: :delete %>
  <% end %>

  

<!--Comments-->
<div class="sub-content">
<h3>별점과 함께 댓글을 남겨주세요</h3>
<div class="gap"></div>

    <%= form_tag("/shops/#{@shop.id}/comments", method: "post") do %>
      <%= text_field_tag(:content) %>
      <%= submit_tag("Submit") %>
    <% end %>
<div class="gap"></div>

<% @comments.each do |comment| %>
  <%= comment.content %>
    <% if comment.user_id == current_user.id %>
      <a href = '/shops/<%= @shop.id %>/comments/<%= comment.id %>'
         data-method = 'delete' 
         data-confirm = '댓글을 삭제합니다.'>[x]
      </a>
      </div>
      </div>
    <% end %>
  <br>
<% end %>
</div>