config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :posts, :products, :orders
  
  resources :shops, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
  
  get 'shops/result' => 'shops#result', as: "result"
  get '/pay/:id' => 'shops#pay'
  get  '/near_shop' => 'shopw#near_shop'
  post '/write'=> 'shops#write'
  get "/location" => "shops#location"
  post 'shops/near_shop'
    
  
  
  get 'products/index' => 'products#index'
  
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  get 'line_items/check_order' => 'line_items#check_order', as: "my_order"
  get 'line_items/new/:id' => 'line_items#new', as: "line_items_new"
  get 'line_items/okay' => 'line_items#okay', as: "okay"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post '/line_items/:product_id' => "line_items#create"
  post 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  get 'okay/accept/:id' => 'line_items#accept',as: "accept"
  get 'okay/deny/:id' => 'line_items#deny',as: "deny"
  
  get '/orders/index' => "orders#index"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      if user.nil? 
        can :read, :all
      elsif user.has_role? 'customer'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
      elsif user.has_role? 'manager'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
      elsif user.has_role? 'admin'
      can [:read, :create, :update, :destroy], :all
      
      elsif user.has_role? 'manager'
        can [:read, :create], :all
        can [:update, :destroy], Post, user_id: user.id
        
      elsif user.has_role? 'admin'
        can [:read, :create, :update, :destroy], :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :shop
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  belongs_to :shop
  belongs_to :user
  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    resourcify
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    belongs_to :shop
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shop.rb
class Shop < ActiveRecord::Base
    # 여러 메뉴를 가지고 있다
    has_many :menus
    has_many :products
    has_many :comments
    has_many :favorite
    has_many :users, through: :favorite
    
    def self.search(search)
      where("name LIKE ?", "%#{search}%") 
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorite
  has_many :shops, through: :favorite
  has_many :posts
  has_many :favorites
  has_many :comments
  has_many :line_items
  
  after_create :assign_default_role
  def assign_default_role
    self.add_role(:customer) if self.roles.blank?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-1.12.4.js"
    integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
    crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "main.css" %>
         
    <!-- www.google.com/fonts -->
<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
</head>
<body>

  
  <div class="content">
  <!--  <div class="bu">-->
  <!--			<button>button 3d</button>-->
  <!--			<button>button 3d</button>-->
  <!--			<button>button 3d</button>-->
		<!--</div>-->
		
	
  <header>
    <nav id="mainNav" class="navar navbar-fixed-top">
     
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only navbar-default">Toggle navigation</span>메뉴<i class="fa fa-bars"></i>
				</button>
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="/">CafeIn</a></li>
				<!--<img id="logo" src="/image/brand.png" alt="logo" />-->
<!--				<li><%= link_to href: '/' do %>-->
<!--    <%= image_tag '/image/brand.png', class:"navbar-brand", alt: 'a face that is unnervingly happy'%>-->
<!--<% end %></li>-->
				</ul>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					 <% if user_signed_in? %>
						<li><a><strong><%= current_user.username %></strong></a></li>
						<li><%= link_to '프로필 수정', edit_user_registration_path %></li>
            <li><%= link_to '로그아웃', destroy_user_session_path, method: :delete, :data => {:confirm => 'Are you sure?'} %></li>
            <li><%= link_to '즐겨찾는 카페', favorites_path %></li>
            <li><%= link_to '장바구니', cart_path(:id => @current_cart.id) %></li>
            <% if current_user.id > 20 %>
              <li><%= link_to '주문', my_order_path %></li>
            <% end %>
          <% else %>
          	<li><%= link_to '로그인', new_user_session_path %></li>
          	<li><%= link_to '회원가입', new_user_registration_path %></li>
          <% end %>
          <li><%= link_to 'Q&A', posts_path %></li>
          <!--<li><a href = 'products'>가맹점주 메뉴 등록</a></li>-->
				</ul>
			</div>
			 
		</div>

	</nav>
	
    
  </header>

<%= yield %>

</div>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>